// The app shell a returning visitor needs offline: every page, script, style
// and icon (not narration audio or videos). Versioned by content, so any
// change installs a fresh cache and old ones are dropped.
import { createHash } from "node:crypto";
import { readFile, readdir } from "node:fs/promises";
import { join, relative } from "node:path";

const SHELL_DIRS = ["js", "css", "assets/icons", "e"];
const SHELL_FILES = ["index.html", "manifest.webmanifest", "assets/logo.png", "assets/narration/manifest.json"];

async function walk(root, dir) {
  const entries = await readdir(join(root, dir), { withFileTypes: true }).catch(() => []);
  const nested = await Promise.all(entries.map((e) => (e.isDirectory() ? walk(root, join(dir, e.name)) : [join(dir, e.name)])));
  return nested.flat();
}

export async function precacheList(root) {
  const files = [...SHELL_FILES, ...(await Promise.all(SHELL_DIRS.map((dir) => walk(root, dir)))).flat()]
    .map((path) => relative(root, join(root, path)).split("\\").join("/"))
    .filter((path) => /\.(html|js|css|png|webmanifest|json)$/.test(path))
    .sort();
  const hash = createHash("sha256");
  for (const path of files) hash.update(path).update(await readFile(join(root, path)));
  return { version: hash.digest("hex").slice(0, 12), files: files.map((path) => `/${path}`) };
}

export const precacheSource = ({ version, files }) =>
  `// Generated by tools/build-pages.mjs — do not edit.\nself.DYK_PRECACHE = ${JSON.stringify({ version, files }, null, 2)};\n`;
