// Stamps sw.js with the app-shell precache list and a version derived from those files' contents,
// so every deploy that changes the shell gets a fresh cache (and old caches are deleted on activate).
import { createHash } from "node:crypto";
import { existsSync, readdirSync, readFileSync } from "node:fs";
import { join } from "node:path";

const SHELL_PAGES = { "/": "index.html", "/offline/": "offline/index.html", "/collection/": "collection/index.html" };
const SHELL_FILES = [
  "/css/site.css",
  "/manifest.webmanifest",
  "/favicon.ico",
  "/data/episodes.json",
  "/assets/brand/avatar-192.webp",
  "/assets/brand/avatar-384.webp",
  "/assets/icons/icon-192.png",
];
const BUILD_BLOCK = /\/\/ BUILD:START[^\n]*\n[\s\S]*?\/\/ BUILD:END/;

const listFiles = (root, dir, pattern) =>
  existsSync(join(root, dir))
    ? readdirSync(join(root, dir), { recursive: true })
        .map(String)
        .filter((name) => pattern.test(name))
        .sort()
        .map((name) => `/${dir}/${name.split("\\").join("/")}`)
    : [];

/** Every URL the service worker precaches. */
export function precacheList(root) {
  return [...Object.keys(SHELL_PAGES), ...SHELL_FILES, ...listFiles(root, "js", /\.js$/), ...listFiles(root, "fonts", /\.woff2$/)];
}

/** A short hash of the precached files; generated pages are read from `files` (this build), the rest from disk. */
export function shellVersion(root, files, precache) {
  const hash = createHash("sha256");
  for (const url of precache) {
    const path = SHELL_PAGES[url] ?? url.slice(1);
    hash.update(url).update(files[path] ?? readFileSync(join(root, path)));
  }
  return hash.digest("hex").slice(0, 12);
}

/** sw.js text with its BUILD block replaced. */
export function stampServiceWorker(source, { version, precache }) {
  if (!BUILD_BLOCK.test(source)) throw new Error("sw.js: missing the // BUILD:START … // BUILD:END block");
  const block = `// BUILD:START (generated by tools/build-site.mjs — do not edit)\nconst VERSION = ${JSON.stringify(version)};\nconst PRECACHE = ${JSON.stringify(precache, null, 2)};\n// BUILD:END`;
  return source.replace(BUILD_BLOCK, block);
}
