// Service worker for the installable app (dexty.live).
// - App shell (pages, CSS, JS, fonts, logo) precached under a versioned cache; the version and the
//   list below are stamped by tools/build-site.mjs from the files' contents — do not edit them by hand.
// - HTML: network first, so a newly published episode shows up at once; cached copy or the branded
//   offline page when there is no connection.
// - data/episodes.json and artwork: stale-while-revalidate.
// - Never touches third-party requests (YouTube player, i.ytimg.com thumbnails, the newsletter
//   provider): those go straight to the network and are never cached.
// - On activate, deletes every cache that is not ours — including the old game's — and reloads tabs
//   that the old game's worker was serving.

// BUILD:START (generated by tools/build-site.mjs — do not edit)
const VERSION = "481cbdc60d6a";
const PRECACHE = [
  "/",
  "/offline/",
  "/collection/",
  "/css/site.css",
  "/manifest.webmanifest",
  "/favicon.ico",
  "/data/episodes.json",
  "/assets/brand/avatar-192.webp",
  "/assets/brand/avatar-384.webp",
  "/assets/icons/icon-192.png",
  "/js/lib/catalog-client.js",
  "/js/lib/install.js",
  "/js/lib/kid-names.js",
  "/js/lib/player-name.js",
  "/js/lib/profile.js",
  "/js/lib/progress-client.js",
  "/js/lib/progress.js",
  "/js/lib/random-word.js",
  "/js/lib/search.js",
  "/js/site.js",
  "/js/ui/collection.js",
  "/js/ui/hero.js",
  "/js/ui/install.js",
  "/js/ui/not-found.js",
  "/js/ui/player.js",
  "/js/ui/profile.js",
  "/js/ui/quiz.js",
  "/js/ui/search-ui.js",
  "/js/ui/surprise.js",
  "/fonts/inter-latin-400-normal.woff2",
  "/fonts/inter-latin-600-normal.woff2",
  "/fonts/montserrat-latin-800-normal.woff2",
  "/fonts/montserrat-latin-900-normal.woff2",
  "/fonts/newsreader-latin-400-italic.woff2",
  "/fonts/newsreader-latin-500-normal.woff2"
];
// BUILD:END

const SHELL = `dexty-shell-${VERSION}`;
const RUNTIME = "dexty-runtime-v1";
const PAGES = "dexty-pages-v1";
const OURS = [SHELL, RUNTIME, PAGES];
const OFFLINE_URL = "/offline/";
const STALE_WHILE_REVALIDATE = [/^\/data\/episodes\.json$/, /^\/assets\/(episodes|brand)\//];
const RUNTIME_MAX_ENTRIES = 60;

const cacheable = (response) => response && response.ok && response.type === "basic";

self.addEventListener("install", (event) => {
  event.waitUntil(
    caches
      .open(SHELL)
      .then((cache) => cache.addAll(PRECACHE.map((url) => new Request(url, { cache: "reload" }))))
      .then(() => self.skipWaiting()),
  );
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    (async () => {
      const stale = (await caches.keys()).filter((key) => !OURS.includes(key));
      await Promise.all(stale.map((key) => caches.delete(key)));
      await self.clients.claim();
      // Caches we never made belong to the retired game: reload the tabs it was serving.
      if (stale.some((key) => !key.startsWith("dexty-"))) {
        const windows = await self.clients.matchAll({ type: "window" });
        await Promise.all(windows.map((client) => client.navigate(client.url).catch(() => undefined)));
      }
    })(),
  );
});

async function networkFirst(request) {
  try {
    const response = await fetch(request);
    if (cacheable(response)) {
      const copy = response.clone();
      caches.open(PAGES).then((cache) => cache.put(request, copy)).catch(() => undefined);
    }
    return response;
  } catch {
    return (await caches.match(request)) ?? (await caches.match(OFFLINE_URL)) ?? Response.error();
  }
}

async function trim(cache) {
  const keys = await cache.keys();
  await Promise.all(keys.slice(0, Math.max(0, keys.length - RUNTIME_MAX_ENTRIES)).map((key) => cache.delete(key)));
}

async function staleWhileRevalidate(event) {
  const cache = await caches.open(RUNTIME);
  const cached = (await cache.match(event.request)) ?? (await caches.match(event.request));
  const network = fetch(event.request)
    .then(async (response) => {
      if (cacheable(response)) {
        await cache.put(event.request, response.clone());
        await trim(cache);
      }
      return response;
    })
    .catch(() => cached ?? Response.error());
  event.waitUntil(network.then(() => undefined, () => undefined));
  return cached ?? network;
}

async function cacheFirst(request) {
  return (await caches.match(request)) ?? fetch(request);
}

self.addEventListener("fetch", (event) => {
  const { request } = event;
  if (request.method !== "GET" || request.headers.has("range")) return;
  const url = new URL(request.url);
  if (url.origin !== self.location.origin || url.pathname === "/sw.js") return;
  if (request.mode === "navigate") return event.respondWith(networkFirst(request));
  if (STALE_WHILE_REVALIDATE.some((pattern) => pattern.test(url.pathname))) return event.respondWith(staleWhileRevalidate(event));
  if (PRECACHE.includes(url.pathname)) return event.respondWith(cacheFirst(request));
});
